# Generated by Django 3.2.3 on 2021-10-07 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_profile_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='image',
        ),
    ]
