# Generated by Django 3.2.3 on 2021-10-13 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_blogpost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
